// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "player":return img`
........................
..................beb...
.................beb....
.....bbb......bbbbbb....
.....b2b.....bbeeeeeb...
.bb..b2bb...bbed1feedf..
bbbb.b22b...bee1ffed4c..
bb4bbb22b...beedfbdd44..
.b44bb22bb..deeeee44444b
.bb44bb222b.beeee44444b.
..bb44bbb22bcbeeee22eb..
....bb44442ecbeee2222...
bbbbbbbb442ceeeeeeeeb...
b2222222eeeeeeeeeeeeb...
bb222b44eeeeeeeeeeeeeb..
.bbbb444eeeeeeeceeeeeb..
...bb4dceeeeeeeceeeeeb..
..bb44bdcdeeeeeceeeeeb..
..bbbbcddccbdecceeeeeb..
......bbbdcccdeeeeeebb..
.......bbccccccceeebb...
........bbbcccccbbbb....
..........bbbbbbb44.....
........................
`;
            case "image1":
            case "turkey":return img`
..............................
..............................
..............................
.....bbb........beb...........
.....b2b.......beb............
.bb..b2bb...bbbbbb............
bbbb.b22b..bbeeeeeb...........
bb4bbb22b.bbed1feedf..........
.b44bb22bbbee1ffed4c..........
.bb44bb22bbeedfbdd44..........
..bb44bbbbdeeeee44444.........
....bb4dddbbeee44444..........
bbbbbbbbdeeeeeee22............
b222222eeeeeeeeeeeb...........
bb222beeeeeebeeeeeb...........
.bbbbbeeeeeebeeeeeb...........
...bbcdceeeedeeeeeb...........
..bb4cbdcdeebeeeeeb...........
..bbbbcddccbdeeeeed...........
.......cbdddddeee44...........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
